### ISSUE TITLE
Building the game kills thrusters 

### ISSUE THREAD

**Issue by FireWaterGasoline** [kirijiri/GalactosIntolerant#38]
Came across a very strange bug. If it even is a bug. 

I was recording myself playing in editor with fraps when I realized that as soon as I hit record the thruster controller only plays low thrusters and completely ignores any others. Stop recording - everything goes to normal. 

So I decided to make a build and see if that helps. In the build you don't even need fraps, non-low thrusters just don't come on at all. 

I messed around with project quality settings and the only way I got a build to work close to what we see in the editor (when pressing play) is by setting frame rate cap to 30 buy forcing double vsync. It's still not the same thing, the high thrusters go out way too quick but at least they even appear. My googling didn't really help. There are people with similar problems but no solutions. 

Can frame rate mess with transitions? Is that even possible? If so, why isn't it messing up other transitions?

**Comment by FireWaterGasoline** [comment]
Update: tripling the thruster accel scale in tinker seems to be solving the problem. I guess acceleration calculation is frame rate dependent and at higher frame rate it just doesn't think the ship ever needs high thrust?

**Comment by cheezopath** [comment]
Maybe the calculation should be locked at 30 for reliable results?

**Comment by disusedgenius** [comment]
Nah, I just forgot to use deltatime, I think. Should be fixed now though,

**Comment by FireWaterGasoline** [comment]
It still doesn't exactly match what's happening when you press play in the
editor but it does work. Thanks, Pete!

**Comment by disusedgenius** [comment]
Hum, that is a bit odd, will leave this open and investigate further if I get a chance. Need a way to cripple my frame rate, I guess to test it properly

**Comment by cheezopath** [comment]
fraps is easiest way i think....was it free or cheap i dont remember. We
can test it over here if need be

**Comment by disusedgenius** [comment]
Yeah, let's check on the weekend. If I do fixes this week then it'll just be the simple, non-thinking stuff. :)
